repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
        files: requirements.ini
    -   id: pretty-format-json
        args:
            - "--autofix"
            - "--indent=2"
            - "--no-sort-keys"
        exclude_types: [jupyter]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --in-place]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.0'
    hooks:
    -   id: mypy
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile=black"]
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'  # add version here
    hooks:
    -   id: poetry-check
        args: ["-C", "./botornot"]
    -   id: poetry-lock
        args: ["-C", "./botornot"]
    -   id: poetry-install
        args: ["-C", "./botornot"]
